version: '2'

services:
  main:
    image: gxic-rit-image
    ports:
      - 5000:5000
    build: .
    volumes:
      - .:/source
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=gxic_rit/walson/server.py

  dlib_server:
    image: gxic-rit-image
    build: .
    volumes:
      - .:/source
    working_dir: /source
    environment:
      - FLASK_APP=scripts/dlib_server.py
    command: flask run --host 0.0.0.0
    ports:
      - 5001:5000
